[2025-03-13T18:14:38.032+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-13T18:14:38.043+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: andrew_access_files.print_from_files manual__2025-03-13T18:14:34.678985+00:00 [queued]>
[2025-03-13T18:14:38.049+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: andrew_access_files.print_from_files manual__2025-03-13T18:14:34.678985+00:00 [queued]>
[2025-03-13T18:14:38.049+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-03-13T18:14:38.068+0000] {taskinstance.py:2890} INFO - Executing <Task(_PythonDecoratedOperator): print_from_files> on 2025-03-13 18:14:34.678985+00:00
[2025-03-13T18:14:38.077+0000] {standard_task_runner.py:72} INFO - Started process 1661717 to run task
[2025-03-13T18:14:38.081+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'andrew_access_files', 'print_from_files', 'manual__2025-03-13T18:14:34.678985+00:00', '--job-id', '69', '--raw', '--subdir', 'DAGS_FOLDER/access_other_files.py', '--cfg-path', '/tmp/tmpw3knun0w']
[2025-03-13T18:14:38.082+0000] {standard_task_runner.py:105} INFO - Job 69: Subtask print_from_files
[2025-03-13T18:14:38.130+0000] {task_command.py:467} INFO - Running <TaskInstance: andrew_access_files.print_from_files manual__2025-03-13T18:14:34.678985+00:00 [running]> on host ubuntu-s-2vcpu-4gb-amd-sfo3-01
[2025-03-13T18:14:38.206+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='andrew_access_files' AIRFLOW_CTX_TASK_ID='print_from_files' AIRFLOW_CTX_EXECUTION_DATE='2025-03-13T18:14:34.678985+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-13T18:14:34.678985+00:00'
[2025-03-13T18:14:38.208+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-03-13T18:14:38.208+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-03-13T18:14:38.208+0000] {logging_mixin.py:190} INFO - Current task name:print_from_files state:running start_date:2025-03-13 18:14:38.044222+00:00
[2025-03-13T18:14:38.208+0000] {logging_mixin.py:190} INFO - Dag name:andrew_access_files and current dag run status:running
[2025-03-13T18:14:38.208+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-13T18:14:38.209+0000] {logging_mixin.py:190} INFO - hello world!
[2025-03-13T18:14:38.210+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/root/venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/venv/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/venv/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/venv/lib/python3.12/site-packages/airflow/decorators/base.py", line 266, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/venv/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/venv/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/venv/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/venv/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/airflow/dags/access_other_files.py", line 19, in access_and_print
    with os.scandir("../other_python_shenanigans") as scannedfiles:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '../other_python_shenanigans'
[2025-03-13T18:14:38.219+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-03-13T18:14:38.219+0000] {logging_mixin.py:190} INFO - Task start:2025-03-13 18:14:38.044222+00:00 end:2025-03-13 18:14:38.218818+00:00 duration:0.174596
[2025-03-13T18:14:38.220+0000] {logging_mixin.py:190} INFO - Task:<Task(_PythonDecoratedOperator): print_from_files> dag:<DAG: andrew_access_files> dagrun:<DagRun andrew_access_files @ 2025-03-13 18:14:34.678985+00:00: manual__2025-03-13T18:14:34.678985+00:00, state:running, queued_at: 2025-03-13 18:14:34.706144+00:00. externally triggered: True>
[2025-03-13T18:14:38.220+0000] {logging_mixin.py:190} INFO - Failure caused by [Errno 2] No such file or directory: '../other_python_shenanigans'
[2025-03-13T18:14:38.220+0000] {taskinstance.py:1226} INFO - Marking task as FAILED. dag_id=andrew_access_files, task_id=print_from_files, run_id=manual__2025-03-13T18:14:34.678985+00:00, execution_date=20250313T181434, start_date=20250313T181438, end_date=20250313T181438
[2025-03-13T18:14:38.245+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-13T18:14:38.246+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 69 for task print_from_files ([Errno 2] No such file or directory: '../other_python_shenanigans'; 1661717)
Traceback (most recent call last):
  File "/root/venv/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/venv/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/root/venv/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/root/venv/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/venv/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/venv/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/root/venv/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/root/venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/root/venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/venv/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/venv/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/venv/lib/python3.12/site-packages/airflow/decorators/base.py", line 266, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/venv/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/venv/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/venv/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/venv/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/airflow/dags/access_other_files.py", line 19, in access_and_print
    with os.scandir("../other_python_shenanigans") as scannedfiles:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '../other_python_shenanigans'
[2025-03-13T18:14:38.296+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-03-13T18:14:38.309+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-13T18:14:38.310+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
