[2025-04-04T15:05:14.887+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-04T15:05:14.902+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: check_queries.test2 manual__2025-04-04T15:05:09.468182+00:00 [queued]>
[2025-04-04T15:05:14.910+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: check_queries.test2 manual__2025-04-04T15:05:09.468182+00:00 [queued]>
[2025-04-04T15:05:14.911+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-04-04T15:05:14.935+0000] {taskinstance.py:2890} INFO - Executing <Task(_PythonDecoratedOperator): test2> on 2025-04-04 15:05:09.468182+00:00
[2025-04-04T15:05:14.943+0000] {standard_task_runner.py:72} INFO - Started process 1962542 to run task
[2025-04-04T15:05:14.949+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'check_queries', 'test2', 'manual__2025-04-04T15:05:09.468182+00:00', '--job-id', '103', '--raw', '--subdir', 'DAGS_FOLDER/check_queries_prototype.py', '--cfg-path', '/tmp/tmphjikv9qz']
[2025-04-04T15:05:14.950+0000] {standard_task_runner.py:105} INFO - Job 103: Subtask test2
[2025-04-04T15:05:15.002+0000] {task_command.py:467} INFO - Running <TaskInstance: check_queries.test2 manual__2025-04-04T15:05:09.468182+00:00 [running]> on host ubuntu-s-2vcpu-4gb-amd-sfo3-01
[2025-04-04T15:05:15.082+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='check_queries' AIRFLOW_CTX_TASK_ID='test2' AIRFLOW_CTX_EXECUTION_DATE='2025-04-04T15:05:09.468182+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-04T15:05:09.468182+00:00'
[2025-04-04T15:05:15.085+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-04-04T15:05:15.085+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-04-04T15:05:15.086+0000] {logging_mixin.py:190} INFO - Current task name:test2 state:running start_date:2025-04-04 15:05:14.903263+00:00
[2025-04-04T15:05:15.086+0000] {logging_mixin.py:190} INFO - Dag name:check_queries and current dag run status:running
[2025-04-04T15:05:15.087+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-04-04T15:05:15.088+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/root/venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/venv/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/venv/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/venv/lib/python3.12/site-packages/airflow/decorators/base.py", line 266, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/venv/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/venv/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/venv/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/venv/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/airflow/dags/check_queries_prototype.py", line 26, in individual_query_check
    results = client.query(query.read())
                           ^^^^^
NameError: name 'query' is not defined
[2025-04-04T15:05:15.100+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-04-04T15:05:15.100+0000] {logging_mixin.py:190} INFO - Task start:2025-04-04 15:05:14.903263+00:00 end:2025-04-04 15:05:15.099868+00:00 duration:0.196605
[2025-04-04T15:05:15.101+0000] {logging_mixin.py:190} INFO - Task:<Task(_PythonDecoratedOperator): test2> dag:<DAG: check_queries> dagrun:<DagRun check_queries @ 2025-04-04 15:05:09.468182+00:00: manual__2025-04-04T15:05:09.468182+00:00, state:running, queued_at: 2025-04-04 15:05:09.542648+00:00. externally triggered: True>
[2025-04-04T15:05:15.101+0000] {logging_mixin.py:190} INFO - Failure caused by name 'query' is not defined
[2025-04-04T15:05:15.101+0000] {taskinstance.py:1226} INFO - Marking task as FAILED. dag_id=check_queries, task_id=test2, run_id=manual__2025-04-04T15:05:09.468182+00:00, execution_date=20250404T150509, start_date=20250404T150514, end_date=20250404T150515
[2025-04-04T15:05:15.135+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-04-04T15:05:15.136+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 103 for task test2 (name 'query' is not defined; 1962542)
Traceback (most recent call last):
  File "/root/venv/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/venv/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/root/venv/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/root/venv/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/venv/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/venv/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/root/venv/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/root/venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/root/venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/venv/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/venv/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/venv/lib/python3.12/site-packages/airflow/decorators/base.py", line 266, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/venv/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/venv/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/venv/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/venv/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/airflow/dags/check_queries_prototype.py", line 26, in individual_query_check
    results = client.query(query.read())
                           ^^^^^
NameError: name 'query' is not defined
[2025-04-04T15:05:15.163+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-04-04T15:05:15.177+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-04T15:05:15.178+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
