[2025-03-27T20:05:39.825+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-27T20:05:39.836+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: run_external_queries.use_bigquery manual__2025-03-27T20:05:36.376281+00:00 [queued]>
[2025-03-27T20:05:39.841+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: run_external_queries.use_bigquery manual__2025-03-27T20:05:36.376281+00:00 [queued]>
[2025-03-27T20:05:39.842+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-03-27T20:05:39.855+0000] {taskinstance.py:2890} INFO - Executing <Task(_PythonDecoratedOperator): use_bigquery> on 2025-03-27 20:05:36.376281+00:00
[2025-03-27T20:05:39.861+0000] {standard_task_runner.py:72} INFO - Started process 1861684 to run task
[2025-03-27T20:05:39.865+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'run_external_queries', 'use_bigquery', 'manual__2025-03-27T20:05:36.376281+00:00', '--job-id', '89', '--raw', '--subdir', 'DAGS_FOLDER/run_external_queries.py', '--cfg-path', '/tmp/tmpqfxputff']
[2025-03-27T20:05:39.866+0000] {standard_task_runner.py:105} INFO - Job 89: Subtask use_bigquery
[2025-03-27T20:05:39.907+0000] {task_command.py:467} INFO - Running <TaskInstance: run_external_queries.use_bigquery manual__2025-03-27T20:05:36.376281+00:00 [running]> on host ubuntu-s-2vcpu-4gb-amd-sfo3-01
[2025-03-27T20:05:39.962+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='run_external_queries' AIRFLOW_CTX_TASK_ID='use_bigquery' AIRFLOW_CTX_EXECUTION_DATE='2025-03-27T20:05:36.376281+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-27T20:05:36.376281+00:00'
[2025-03-27T20:05:39.963+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-03-27T20:05:39.964+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-03-27T20:05:39.964+0000] {logging_mixin.py:190} INFO - Current task name:use_bigquery state:running start_date:2025-03-27 20:05:39.837343+00:00
[2025-03-27T20:05:39.964+0000] {logging_mixin.py:190} INFO - Dag name:run_external_queries and current dag run status:running
[2025-03-27T20:05:39.964+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-27T20:05:40.064+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/root/venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/venv/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/venv/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/venv/lib/python3.12/site-packages/airflow/decorators/base.py", line 266, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/venv/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/venv/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/venv/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/venv/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/airflow/dags/run_external_queries.py", line 23, in use_bigquery
    query = open(currentdir + "/queries/" + foundfile)
                 ~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~
TypeError: can only concatenate str (not "posix.DirEntry") to str
[2025-03-27T20:05:40.071+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-03-27T20:05:40.072+0000] {logging_mixin.py:190} INFO - Task start:2025-03-27 20:05:39.837343+00:00 end:2025-03-27 20:05:40.071347+00:00 duration:0.234004
[2025-03-27T20:05:40.072+0000] {logging_mixin.py:190} INFO - Task:<Task(_PythonDecoratedOperator): use_bigquery> dag:<DAG: run_external_queries> dagrun:<DagRun run_external_queries @ 2025-03-27 20:05:36.376281+00:00: manual__2025-03-27T20:05:36.376281+00:00, state:running, queued_at: 2025-03-27 20:05:36.399755+00:00. externally triggered: True>
[2025-03-27T20:05:40.072+0000] {logging_mixin.py:190} INFO - Failure caused by can only concatenate str (not "posix.DirEntry") to str
[2025-03-27T20:05:40.072+0000] {taskinstance.py:1226} INFO - Marking task as FAILED. dag_id=run_external_queries, task_id=use_bigquery, run_id=manual__2025-03-27T20:05:36.376281+00:00, execution_date=20250327T200536, start_date=20250327T200539, end_date=20250327T200540
[2025-03-27T20:05:40.089+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-27T20:05:40.090+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 89 for task use_bigquery (can only concatenate str (not "posix.DirEntry") to str; 1861684)
Traceback (most recent call last):
  File "/root/venv/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/venv/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/root/venv/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/root/venv/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/venv/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/venv/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/root/venv/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/root/venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/root/venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/venv/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/venv/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/venv/lib/python3.12/site-packages/airflow/decorators/base.py", line 266, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/venv/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/venv/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/venv/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/venv/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/airflow/dags/run_external_queries.py", line 23, in use_bigquery
    query = open(currentdir + "/queries/" + foundfile)
                 ~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~
TypeError: can only concatenate str (not "posix.DirEntry") to str
[2025-03-27T20:05:40.118+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-03-27T20:05:40.130+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-27T20:05:40.131+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
